### ISSUE TITLE
I got this issue when running make test

### ISSUE THREAD

**Issue by wreckitral** [igor-baiborodine/distributed-services-with-go-workshop#45]
protoc --version
libprotoc 28.3

protoc-gen-go --version
protoc-gen-go v1.35.2

└─$ make test
go test -race ./...
# github.com/igor-baiborodine/proglog/api/v1
api/v1/log_grpc.pb.go:19:16: undefined: grpc.SupportPackageIsVersion9
api/v1/log_grpc.pb.go:35:88: undefined: grpc.ServerStreamingClient
api/v1/log_grpc.pb.go:36:68: undefined: grpc.BidiStreamingClient
api/v1/log_grpc.pb.go:68:107: undefined: grpc.ServerStreamingClient
api/v1/log_grpc.pb.go:85:37: undefined: grpc.ServerStreamingClient
api/v1/log_grpc.pb.go:98:37: undefined: grpc.BidiStreamingClient
api/v1/log_grpc.pb.go:116:38: undefined: grpc.ServerStreamingServer
api/v1/log_grpc.pb.go:117:21: undefined: grpc.BidiStreamingServer
api/v1/log_grpc.pb.go:210:37: undefined: grpc.ServerStreamingServer
api/v1/log_grpc.pb.go:217:37: undefined: grpc.BidiStreamingServer
api/v1/log_grpc.pb.go:68:107: too many errors
FAIL    github.com/igor-baiborodine/proglog/api/v1 [build failed]
FAIL    github.com/igor-baiborodine/proglog/cmd/getservers [build failed]
# github.com/igor-baiborodine/proglog/github.com/igor-baiborodine/api/log_v1
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:19:16: undefined: grpc.SupportPackageIsVersion9
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:35:88: undefined: grpc.ServerStreamingClient
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:36:68: undefined: grpc.BidiStreamingClient
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:68:107: undefined: grpc.ServerStreamingClient
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:85:37: undefined: grpc.ServerStreamingClient
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:98:37: undefined: grpc.BidiStreamingClient
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:116:38: undefined: grpc.ServerStreamingServer
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:117:21: undefined: grpc.BidiStreamingServer
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:210:37: undefined: grpc.ServerStreamingServer
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:217:37: undefined: grpc.BidiStreamingServer
github.com/igor-baiborodine/api/log_v1/log_grpc.pb.go:68:107: too many errors
FAIL    github.com/igor-baiborodine/proglog/cmd/proglog [build failed]
FAIL    github.com/igor-baiborodine/proglog/github.com/igor-baiborodine/api/log_v1 [build failed]
FAIL    github.com/igor-baiborodine/proglog/internal/agent [build failed]
?       github.com/igor-baiborodine/proglog/internal/auth       [no test files]
?       github.com/igor-baiborodine/proglog/internal/config     [no test files]
FAIL    github.com/igor-baiborodine/proglog/internal/loadbalance [build failed]
ok      github.com/igor-baiborodine/proglog/internal/discovery  (cached)
FAIL    github.com/igor-baiborodine/proglog/internal/log [build failed]
FAIL    github.com/igor-baiborodine/proglog/internal/server [build failed]
FAIL
make: *** [Makefile:63: test] Error 1

**Comment by igor-baiborodine** [comment]
@wreckitral, try executing `go get google.golang.org/grpc@latest`, then `make compile test`.

**Comment by wreckitral** [comment]
okay, thank you
